print("Belanja Otomatis".center(40,"="))
barang = (input("Masukan nama barang \t: "))
jumlah = int(input("Masukan jumlah barang \t: "))
harga = int(input("Masukan harga satuan \t: "))
print("\n")
print("Struk Belanja".center(40,"="))
print(f"Nama Barang \t: {barang:>10}")
print(f"Jumlah Barang \t: {jumlah:>10}")
print(f"Harga pcs \t: {harga:>10}")
print(f"Total harga \t: {jumlah*harga:>10,}")